FROM golang:1.10.3
MAINTAINER Neutron37 <neutron37@indieops.berlin>

COPY . /go/src/probe
WORKDIR /go/src/probe

RUN go get ./... \
    && CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-w -s' -o /target/probe .
